import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";

// The pdf.js worker normally runs in its own Worker thread, loaded from a
// separate file by URL at runtime. It CANNOT ship as a standalone file next
// to main.js the way it does in local dev — Obsidian's community-plugin
// installer only ever downloads main.js/manifest.json/styles.css from a
// release, never a 4th asset, so a separately-shipped worker file 404s for
// every real user (confirmed: net::ERR_FILE_NOT_FOUND on a real install).
// Embedding its source as a string and constructing a Blob URL at runtime
// (see PdfViewer.ts) avoids needing a second file at all.
const workerSource = readFileSync("node_modules/pdfjs-dist/build/pdf.worker.min.mjs", "utf8");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    __PDF_WORKER_SOURCE__: JSON.stringify(workerSource),
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
