import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync } from "node:fs";

// The pdf.js worker runs in its own Worker thread, loaded by URL at runtime —
// it must never be bundled into main.js. Copied once; it doesn't change
// between our own rebuilds since it's a static node_modules asset.
copyFileSync("node_modules/pdfjs-dist/build/pdf.worker.min.mjs", "pdf.worker.min.mjs");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
